#!/bin/bash
#
# Copyright (c) 2019, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
#

set -e

PYCGA_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
echo "Run Python formatting check..."
flake8 "$PYCGA_DIR"
echo "Run Cython formatting check..."
flake8 "$PYCGA_DIR" --config "$PYCGA_DIR"/.flake8.cython
echo "Run Python docstring conventions check..."
pydocstyle --convention=google "$PYCGA_DIR"
