#!/usr/bin/env python

#
# Copyright (c) 2019, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
#


import argparse
import os.path

from claragenomics.bindings import cuda
from claragenomics.bindings import cudapoa
from claragenomics.io.utils import read_poa_group_file

"""
Sample program for using CUDAPOA Python API for MSA generation.
"""

def run_cudapoa_msa(groups):
def run_cudapoa_consensus(groups):
    """
    Generate consensus for POA groups.

    Args:
        groups : A list of groups (i.e. list of sequences) for which
                 MSA is to be generated.
    """
    # Get avaialble memory information
    free, total = cuda.cuda_get_mem_info(cuda.cuda_get_device())

    # Create batch
    max_sequences_per_poa = 500
    gpu_mem_per_batch = 0.9 * free
    batch = cudapoa.CudaPoaBatch(max_sequences_per_poa, gpu_mem_per_batch, stream=None, output_type="msa")

    # Add poa groups to batch
    initial_count = 0
    for i, group in enumerate(groups):
        group_status, seq_status = batch.add_poa_group(group)
        if (group_status == 0):
            pass

        # Once batch is full, run POA processing
        if ((group_status == 1) or (i == len(groups) - 1)):
            batch.generate_poa()
            msa, status = batch.get_msa()
            batch.reset()
            print("Processed group {} - {}".format(initial_count, i))
            initial_count = i

if __name__ == "__main__":
    cwd = os.path.dirname(os.path.abspath(__file__))
    cga_root = os.path.dirname(os.path.dirname(cwd))
    cudapoa_data_dir = os.path.join(cga_root, "cudapoa", "data")
    sample_windows = os.path.join(cudapoa_data_dir, "sample-windows.txt")
    
    groups = read_window_file(sample_windows, 10000)
    run_cudapoa_msa(groups)
