#!/bin/bash


set -e

PYGW_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
VERSION=`cat $PYGW_DIR/../VERSION`
echo "Run Python doc generation..."
rm -rf $PYGW_DIR/docs
mkdir $PYGW_DIR/docs
cd $PYGW_DIR/docs
sphinx-quickstart -p "GenomeWorks SDK" -v "$VERSION" -a "NVIDIA Corportation" -q --ext-autodoc --sep
##### Update sphinx conf.py with path for modules
sed -i '1s@^@import sys \n@' source/conf.py
sed -i '2s@^@sys.path.insert\(0, "'$PWD'/.."\) \n@' source/conf.py
#####
sphinx-apidoc -f -o source/ ../genomeworks/ ../genomeworks/**/*cpython* ../genomeworks/shared_libs
make html
