#!/bin/bash

#
# Copyright 2019-2020 NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#



set -e

PYGW_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
echo "Run Python formatting check..."
flake8 "$PYGW_DIR"
echo "Run Cython formatting check..."
flake8 "$PYGW_DIR" --config "$PYGW_DIR"/.flake8.cython
echo "Run Python docstring conventions check..."
pydocstyle --convention=google "$PYGW_DIR"
